### ISSUE TITLE
Wheels for other platforms and python versions

### ISSUE THREAD

**Issue by Joeboy** [LeCodeMinister/polars-phonetics#1]
Hi! It looks like this is quite new, but in case you're interested I wanted to use it but immediately came up against the fact it only seems to be built for Python 3.8 on Windows, and I'm using python 3.11 on Linux. For wider usage I think you'd have to update github actions to build versions for each platform / version, or maybe you could build using the stable python api. At least that's my understanding, I'm not super-familiar.

**Comment by LeCodeMinister** [comment]
Hey Joe,

Thanks for pointing this out. 

Yes, polars-phonetics was published only two days ago and is still in early stages of development. 

I'm aware of the fact that the wheels built are very limited. I'm gonna have a look tomorrow to see how I can expand it to other python versions/operating systems. 

Will keep you posted. 

Cheers!

**Comment by LeCodeMinister** [comment]
Hi @Joeboy ,

Apologies for the late fix. But this should be it now. 

Please keep me posted with installing/using the library.

Thanks!
